esphome:
  name: smartmeter
  includes: 
    - sunspec_meter_model.h
    - modbus_server.h
    - smart_meter.h

esp32:
  board: esp32dev
  framework:
    type: arduino

preferences:
  flash_write_interval: 168h

# Enable logging
logger:
  level: INFO

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # 192.168.4.1
  ap:
    ssid: "Smart-Meter Fallback Hotspot"
    password: !secret ap_password

captive_portal:
    
web_server:
  port: 80

uart:
 id: uart_modbus
 tx_pin: 22
 rx_pin: 21
 baud_rate: 9600
 stop_bits: 1
 rx_buffer_size: 1024
 
sensor:
  - platform: wifi_signal
    name: "5.0 WiFi Signal Stärke"
    update_interval: 3s
    filters:
      - median:
          window_size: 5
          send_every: 3
          send_first_at: 1

  - platform: custom
    sensors:
    - name: "SmartMeter"
      id: smart_meter
      internal: true
    # "name" order must match the GetSensors() - m_queries
  #   - name: "4.1 Aussen Temperatur"
  #   - name: "4.2 Warmwasser Temperatur"
  #   - name: "4.3 Mischer Soll Temperatur"
  #   - name: "4.4 Mischer Temperatur"
  #   - name: "4.5 Wp Vorlauf Temperatur"
  #   - name: "4.6 Rücklauf Temperatur"
  #   - name: "4.7 El Verbrauch WW"
  #   - name: "4.8 El Verbrauch Heizen"
    lambda: |-
      auto sm = new sm::SmartMeter(id(uart_modbus));
      App.register_component(sm);
      return sm->GetSensors();
